### ISSUE TITLE
Wikimed crashes on Samsung galaxy A12 with an Android version 12

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android-custom#180]
Here is the feedback sent by our user:

> When ever I try to open the app it tells me to share  this;
Someone has reported a crash
  Hi Kiwix Developers!
The Android app crashed, here are some details to help fix it:
    
      Exception Details:
    java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = kotlinx.coroutines.CoroutinesInternalError)
	at android.os.Parcel.writeSerializable(Parcel.java:2178)
	at android.os.Parcel.writeValue(Parcel.java:1944)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1105)
	at android.content.Intent.writeToParcel(Intent.java:11771)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2867)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1743)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1135)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1106)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:420)
	at org.kiwix.kiwixmobile.core.main.CoreMainActivity$$ExternalSyntheticLambda0.uncaughtException(R8$$SyntheticClass:35)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:73)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:15)
	at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:51)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:170)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:79)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: Em

**Comment by MohitMaliFtechiz** [comment]
@Popolechien This is the full report or do you have more logs?

> When ever I try to open the app it tells me to share this;

The problem is occurring inside the coroutines and throwing the parcelable exception, it is a another issue(I will place a fix for it in a ticket) The logs are not showing the proper error due to this parcelable exception. I confirm this is an issue in if the coroutine throws an error it will not show the actual error instead of it will show the parcelable exception as shown in the below image where I explicitly thow error in the corutine to test this issue.

![Screenshot from 2024-06-26 19-07-47](https://github.com/kiwix/kiwix-android-custom/assets/34593983/688e03f3-d0e2-4b7f-a962-2ce291d1d107)


Apart from this, the behavior as the user describes that at the launch he is facing this issue. It seems it is related to https://github.com/kiwix/kiwix-android/issues/3899. Since in the new version of Wikimed app, we are migrating the history and notes in the room database at the start of the application within the coroutine and it probably throwing the error there.

@kelson42 This issue is related to kiwix android can you please move this issue to kiwix-android repo.

**Comment by Popolechien** [comment]
@MohitMaliDeveloper This is the full report that they shared with me. It would be stranged that they only shared part of it so I'd take it as the full stuff
